export type PermissionName =
  | "dashboard.view"

  | "company.view"
  | "company.create"
  | "company.update"
  | "company.delete"

  | "branch.view"
  | "branch.create"
  | "branch.update"
  | "branch.delete"

  | "user.view"
  | "user.invite"
  | "user.update"

  | "inventory.view"
  | "inventory.create"
  | "inventory.update"
  | "inventory.delete"
  | "inventory.stock.adjust"

  | "supplier.view"
  | "supplier.create"
  | "supplier.update"
  | "supplier.delete"

  | "purchasing.view"
  | "purchasing.create"
  | "purchasing.update"
  | "purchasing.delete"
  | "purchasing.submit"
  | "purchasing.approve"
  | "purchasing.receive"

  | "customer.view"
  | "customer.create"
  | "customer.update"
  | "customer.delete"

  | "quotation.view"
  | "quotation.create"
  | "quotation.update"
  | "quotation.delete"
  | "quotation.send"
  | "quotation.accept"

  | "sales.view"
  | "sales.create"
  | "sales.update"
  | "sales.delete"
  | "sales.confirm"
  | "sales.invoice"

  | "invoice.view"
  | "invoice.create"
  | "invoice.update"
  | "invoice.delete"
  | "invoice.issue"
  | "invoice.payment"

  | "accounting.view"
  | "accounting.debtors.manage"
  | "sales.credit_hold.override"
  | "sales.payment.record"
  | "accounting.accounts.manage"
  | "accounting.journal.create"
  | "accounting.journal.approve"
  | "accounting.journal.post"
  | "accounting.period.manage"
  | "accounting.financial_year.manage"

  | "audit.view"

  | "reports.view"
  | "reports.export"

  | "settings.view"
  | "settings.manage"
  | "settings.company.manage"
  | "settings.branding.manage"
  | "settings.roles.manage"
  | "settings.branches.manage"
  | "settings.finance.view"
  | "settings.finance.manage"
  | "settings.accounting.manage"
  | "settings.security.manage"
  | "settings.notifications.manage"
  | "settings.integrations.manage"
  | "settings.audit.view"
  | "settings.subscription.manage"
  | "data.export"
  | "data.backup"
  | "data.export.audit";
